version: '3.8'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    command: python api_server.py
  
  streamlit:
    build: .
    ports:
      - "8501:8501"
    command: streamlit run Resume_Writer_\(3\).py
    depends_on:
      - api
