name: Keep Render Warm

on:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render API
        run: curl -s https://resume-writer-api.onrender.com/health
